language: generic

git:
  depth: 1

cache:
  directories:
    - $HOME/.stack/
    - $TRAVIS_BUILD_DIR/.stack-work
    - $TRAVIS_BUILD_DIR/nodejs-eval/.stack-work
    - $TRAVIS_BUILD_DIR/nodejs-eval-test/.stack-work

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      group: edge

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-terminal --install-ghc test nodejs-eval-test:nodejs-eval-test
